// src/components/navbar.svelte
<script lang="ts">
    import { getCurrentWindow } from "@tauri-apps/api/window";

    async function closeWindow() {
        await getCurrentWindow().hide();
    }
</script>

<div
    data-tauri-drag-region
    class="flex w-screen p-2 bg-black/50 justify-between items-center"
>
    <span class="text-white/50 font-semibold text-lg">🐈 mood.exe</span>

    <button
        class="text-white/50 p-1 bg-white/8 rounded-md cursor-pointer"
        onclick={closeWindow}
    >
        ❌
    </button>
</div>

// src/components/Navbar.tsx
import WindowClose from "../icons/WindowClose";

export default function Navbar() {
    return (
        <div
            data-tauri-drag-region
            className="bg-white/5 border-b border-[#3f3f3f] flex justify-between"
        >
            <div className="px-4 py-2">
                <span className="text-xl">mood.exe</span>
            </div>

            <button className="cursor-pointer h-full aspect-square hover:bg-red-600">
                <span className="opacity-75 flex justify-center items-center">
                    <WindowClose />
                </span>
            </button>
        </div>
    );
}
